#!/bin/sh -e
/home/root/quickfile/hps_config_fpga /home/root/quickfile/soc_system_dc.rbf
/home/root/countPlayers &
cd /home/root/Minecraft-111/                                             
/usr/java/bin/java -jar minecraft_server.1.11.2.jar 
                                 

